### Ordinal and Nominal Variable

Ordinal variables are the categorical variable in which the categories can be meaningful ordered in simple words we can
measure
Having Order
Example : Rating of product (Good , Very Good, Poor, Excellent)

Nominal variables are the categorical varible that we cann't measure in scale .
Cann't have any order 
Example : (White ,Red, Yellow etc.) or (C,C++,Java,Python,etc)

## Lable Encoding

We apply on ordinal and nominal categorical variables. Example

Grade   Object                                 Grade    Object 

A       Laptop                                   0      1
B       Car    ----Converting Numerical ---->    1      0
C       Mango                                    2      2

Grade  Ordinal variable
Object  Nominal variable

Lable Encoding give numerical values based on the Alphabatical Order

Lable Encoding will create impact on accuracy.

## Ordinal Encoding

We apply on ordinal categorical variables. Example

Grade   Object                                 Grade    Object 

A       Laptop                                   3      Laptop
B       Car    ----Converting Numerical ---->    2      Car
C       Mango                                    1      Mango

Grade  Ordinal variable
Object  Nominal variable

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [9]:
dataFrame = pd.read_csv("D:\\dataSet\\train.csv")

In [10]:
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)

In [12]:
dataFrame.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [14]:
dataFrame.select_dtypes("object").columns   # all the categorical variable

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [15]:
DF2 = dataFrame[["KitchenQual","BldgType"]]

In [16]:
DF2.head()

  KitchenQual BldgType
0          Gd     1Fam
1          TA     1Fam
2          Gd     1Fam
3          Gd     1Fam
4          Gd     1Fam

# LabelEncoder

In [29]:
# Using class LabelEncoder
le = LabelEncoder()

In [30]:
le.fit_transform(DF2["BldgType"])

array([0, 0, 0, ..., 0, 0, 0])

In [31]:
DF2['BldgType_Label_Encoding'] = le.fit_transform(DF2["BldgType"])

C:\Users\DELL\AppData\Local\Temp\ipykernel_12896\2478053977.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['BldgType_Label_Encoding'] = le.fit_transform(DF2["BldgType"])

In [32]:
DF2.head(10)

  KitchenQual BldgType  BldgType_Label_Encoding  KitchenQual_Ord_Emcoding
0          Gd     1Fam                        0                         3
1          TA     1Fam                        0                         2
2          Gd     1Fam                        0                         3
3          Gd     1Fam                        0                         3
4          Gd     1Fam                        0                         3
5          TA     1Fam                        0                         2
6          Gd     1Fam                        0                         3
7          TA     1Fam                        0                         2
8          TA     1Fam                        0                         2
9          TA   2fmCon                        1                         2

# Ordinal Encoding

In [33]:
dataFrame["KitchenQual"].value_counts()

KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64

In [34]:
# Creating Order for Ordinal variable 

order_lable = {"Ex":4,"Gd":3,"TA":2,"Fa":1}

In [35]:
DF2["KitchenQual_Ord_Emcoding"] = DF2["KitchenQual"].map(order_lable)

C:\Users\DELL\AppData\Local\Temp\ipykernel_12896\1591648155.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2["KitchenQual_Ord_Emcoding"] = DF2["KitchenQual"].map(order_lable)

In [36]:
DF2.head(20)

   KitchenQual BldgType  BldgType_Label_Encoding  KitchenQual_Ord_Emcoding
0           Gd     1Fam                        0                         3
1           TA     1Fam                        0                         2
2           Gd     1Fam                        0                         3
3           Gd     1Fam                        0                         3
4           Gd     1Fam                        0                         3
5           TA     1Fam                        0                         2
6           Gd     1Fam                        0                         3
7           TA     1Fam                        0                         2
8           TA     1Fam                        0                         2
9           TA   2fmCon                        1                         2
10          TA     1Fam                        0                         2
11          Ex     1Fam                        0                         4
12          TA     1Fam                        0                         2
13          Gd     1Fam                        0                         3
14          TA     1Fam                        0                         2
15          TA     1Fam                        0                         2
16          TA     1Fam                        0                         2
17          TA   Duplex                        2                         2
18          Gd     1Fam                        0                         3
19          TA     1Fam                        0                         2